# Custom Language File for Launcher Customizer

[ejs.app]
title = "MapleCraft Launcher"

[ejs.landing]
mediaGitHubURL = "https://maplecraft.net"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/NX5xebH"
heroTagline = "下一場冒險，從這裡開始"

[ejs.settings]
tabsAriaLabel = "設定分類"
sourceGithubLink = "https://github.com/lingyu-ily/MapleCraftLauncher"
supportLink = "https://github.com/lingyu-ily/MapleCraftLauncher/issues"

[ejs.welcome]
welcomeHeader = "歡迎來到 MAPLECRAFT"
welcomeDescription = "起源世界已無法滿足世人, 各地英雄開始起身前往更加奇妙且未被探索的其他世界. <br>起身前往探索吧 英雄,帶著原世界居民們祝福的你,在這無盡的宇宙中持續探索."
welcomeDescCTA = "再點幾下，你就能踏上 MAPLECRAFT。"
